# Generated by Django 5.1.5 on 2025-03-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunementor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('apprentice', 'Apprentice')], default='apprentice', max_length=32),
        ),
    ]
