# Generated by Django 5.1.5 on 2025-04-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunementor', '0008_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='tunementor.instrument'),
        ),
    ]
