# Generated by Django 5.1.5 on 2025-04-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunementor', '0010_instructoravailability_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
        migrations.DeleteModel(
            name='InstructorAvailability',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
