# Generated by Django 4.2.16 on 2025-04-07 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('tunementor', '0011_remove_lesson_instructor_remove_lesson_instrument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorCalendar',
            fields=[
                ('calendar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.calendar')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('schedule.calendar',),
        ),
    ]
