# Generated by Django 4.2.16 on 2025-04-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunementor', '0014_booking_cancellation_reason_booking_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='state',
        ),
    ]
