# Generated by Django 4.2.16 on 2025-04-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunementor', '0017_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
